# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227f823155ebc52482781a0e89e32420d2adf96c9758f1379d06e2142678828f314b6629f847d84836a297c47485da0ab29f12805a986883782e6b2ee2403bf1

test:
  secret_key_base: f809572c805211aff66012fee89ffa8cef1090c78216729f4791f004bd1ee55c50b09fa49579a572ea44ee17ef458232bdb9a6e016c109d653aa8a0dde0ef74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
